<a href="https://colab.research.google.com/github/Impossiblepretext/Experiment_No.19-20/blob/main/Covid_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name    Name: Vibhas Shukla
PRN: 25070123140
Branch: F.Y. E&TC (2025–29)
Batch: A1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv("/content/covid_19_data.csv")
data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SNo              306429 non-null  int64
 1   ObservationDate  306429 non-null  object
 2   Province/State   228326 non-null  object
 3   Country/Region   306429 non-null  object
 4   Last Update      306429 non-null  object
 5   Confirmed        306429 non-null  float64
 6   Deaths           306429 non-null  float64
 7   Recovered        306429 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 18.7+ MB

In [ ]:
data['ObservationDate']=data['ObservationDate'].astype('datetime64[ns]')
data['Confirmed']=data['Confirmed'].astype('int64')
data['Deaths']=data['Deaths'].astype('int64')
data['Recovered']=data['Recovered'].astype('int64')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SNo              306429 non-null  int64
 1   ObservationDate  306429 non-null  datetime64[ns]
 2   Province/State   228326 non-null  object
 3   Country/Region   306429 non-null  object
 4   Last Update      306429 non-null  object
 5   Confirmed        306429 non-null  int64
 6   Deaths           306429 non-null  int64
 7   Recovered        306429 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 18.7+ MB

In [ ]:
data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,2020-01-22,Anhui,Mainland China,1/22/2020 17:00,1,0,0
1,2,2020-01-22,Beijing,Mainland China,1/22/2020 17:00,14,0,0
2,3,2020-01-22,Chongqing,Mainland China,1/22/2020 17:00,6,0,0
3,4,2020-01-22,Fujian,Mainland China,1/22/2020 17:00,1,0,0
4,5,2020-01-22,Gansu,Mainland China,1/22/2020 17:00,0,0,0

In [ ]:
### Active Cases
data['Active']=data['Confirmed']-data['Deaths']-data['Recovered']
data.head(50)
data.iloc[50:100]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Active
50,51,2020-01-23,Heilongjiang,Mainland China,1/23/20 17:00,2,0,0,2
51,52,2020-01-23,Henan,Mainland China,1/23/20 17:00,5,0,0,5
52,53,2020-01-23,Hong Kong,Hong Kong,1/23/20 17:00,2,0,0,2
53,54,2020-01-23,Hubei,Mainland China,1/23/20 17:00,444,17,28,399
54,55,2020-01-23,Hunan,Mainland China,1/23/20 17:00,9,0,0,9
55,56,2020-01-23,Inner Mongolia,Mainland China,1/23/20 17:00,0,0,0,0
56,57,2020-01-23,Jiangsu,Mainland China,1/23/20 17:00,5,0,0,5
57,58,2020-01-23,Jiangxi,Mainland China,1/23/20 17:00,7,0,0,7
58,59,2020-01-23,Jilin,Mainland China,1/23/20 17:00,1,0,0,1
59,60,2020-01-23,Liaoning,Mainland China,1/23/20 17:00,3,0,0,3
60,61,2020-01-23,Macau,Macau,1/23/20 17:00,2,0,0,2
61,62,2020-01-23,Ningxia,Mainland China,1/23/20 17:00,1,0,0,1
62,63,2020-01-23,Qinghai,Mainland China,1/23/20 17:00,0,0,0,0
63,64,2020-01-23,Shaanxi,Mainland China,1/23/20 17:00,3,0,0,3
64,65,2020-01-23,Shandong,Mainland China,1/23/20 17:00,6,0,0,6
65,66,2020-01-23,Shanghai,Mainland China,1/23/20 17:00,16,0,0,16
66,67,2020-01-23,Shanxi,Mainland China,1/23/20 17:00,1,0,0,1
67,68,2020-01-23,Sichuan,Mainland China,1/23/20 17:00,8,0,0,8
68,69,2020-01-23,Taiwan,Taiwan,1/23/20 17:00,1,0,0,1
69,70,2020-01-23,Tianjin,Mainland China,1/23/20 17:00,4,0,0,4
70,71,2020-01-23,Tibet,Mainland China,1/23/20 17:00,0,0,0,0
71,72,2020-01-23,Washington,US,1/23/20 17:00,1,0,0,1
72,73,2020-01-23,Xinjiang,Mainland China,1/23/20 17:00,2,0,0,2
73,74,2020-01-23,Yunnan,Mainland China,1/23/20 17:00,2,0,0,2
74,75,2020-01-23,Zhejiang,Mainland China,1/23/20 17:00,27,0,0,27
75,76,2020-01-23,NaN,Japan,1/23/20 17:00,1,0,0,1
76,77,2020-01-23,NaN,Thailand,1/23/20 17:00,4,0,2,2
77,78,2020-01-23,NaN,South Korea,1/23/20 17:00,1,0,0,1
78,79,2020-01-23,NaN,Singapore,1/23/20 17:00,1,0,0,1
79,80,2020-01-23,NaN,Philippines,1/23/20 17:00,0,0,0,0
80,81,2020-01-23,NaN,Malaysia,1/23/20 17:00,0,0,0,0
81,82,2020-01-23,NaN,Vietnam,1/23/20 17:00,2,0,0,2
82,83,2020-01-23,NaN,Australia,1/23/20 17:00,0,0,0,0
83,84,2020-01-23,NaN,Mexico,1/23/20 17:00,0,0,0,0
84,85,2020-01-23,NaN,Brazil,1/23/20 17:00,0,0,0,0
85,86,2020-01-23,NaN,Colombia,1/23/20 17:00,0,0,0,0
86,87,2020-01-23,Unknown,China,1/23/20 17:00,0,0,0,0
87,88,2020-01-23,NaN,Kiribati,1/23/20 17:00,0,0,0,0
88,89,2020-01-24,Hubei,Mainland China,1/24/20 17:00,549,24,31,494
89,90,2020-01-24,Guangdong,Mainland China,1/24/20 17:00,53,0,2,51
90,91,2020-01-24,Zhejiang,Mainland China,1/24/20 17:00,43,0,1,42
91,92,2020-01-24,Beijing,Mainland China,1/24/20 17:00,36,0,1,35
92,93,2020-01-24,Chongqing,Mainland China,1/24/20 17:00,27,0,0,27
93,94,2020-01-24,Hunan,Mainland China,1/24/20 17:00,24,0,0,24
94,95,2020-01-24,Guangxi,Mainland China,1/24/20 17:00,23,0,0,23
95,96,2020-01-24,Shanghai,Mainland China,1/24/20 17:00,20,0,1,19
96,97,2020-01-24,Jiangxi,Mainland China,1/24/20 17:00,18,0,0,18
97,98,2020-01-24,Sichuan,Mainland China,1/24/20 17:00,15,0,0,15
98,99,2020-01-24,Shandong,Mainland China,1/24/20 17:00,15,0,0,15
99,100,2020-01-24,Anhui,Mainland China,1/24/20 17:00,15,0,0,15

In [ ]:
### last/currennt  date
data['ObservationDate'].max()

Timestamp('2021-05-29 00:00:00')

In [ ]:
## Fetch the Latest date data
latest_data=data[data['ObservationDate']==data['ObservationDate'].max()]
latest_data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Active
305664,305665,2021-05-29,NaN,Afghanistan,2021-05-30 04:20:55,70111,2899,57281,9931
305665,305666,2021-05-29,NaN,Albania,2021-05-30 04:20:55,132297,2449,129215,633
305666,305667,2021-05-29,NaN,Algeria,2021-05-30 04:20:55,128456,3460,89419,35577
305667,305668,2021-05-29,NaN,Andorra,2021-05-30 04:20:55,13693,127,13416,150
305668,305669,2021-05-29,NaN,Angola,2021-05-30 04:20:55,34180,757,27646,5777

In [ ]:
latest_data.shape

(765, 9)

In [ ]:
latest_data['Country/Region'].value_counts()

Country/Region
Russia                83
US                    58
Japan                 49
India                 37
Colombia              34
                      ..
Venezuela              1
Vietnam                1
West Bank and Gaza     1
Hong Kong              1
Macau                  1
Name: count, Length: 195, dtype: int64

In [ ]:
latest_data['Country/Region'].nunique()

195

In [ ]:
latest_data['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Diamond Princess',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Micronesia',
       'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Namibia', 'Nepal', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Korea', 'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Uganda', 'United Arab Emirates', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'West Bank and Gaza', 'Yemen', 'Zambia', 'Zimbabwe', 'Italy',
       'Brazil', 'Russia', 'Mexico', 'Japan', 'US', 'Canada', 'Colombia',
       'Peru', 'Spain', 'India', 'UK', 'Mainland China', 'Chile',
       'Belgium', 'Netherlands', 'Australia', 'Pakistan', 'Germany',
       'Sweden', 'Ukraine', 'Hong Kong', 'Macau'], dtype=object)

In [ ]:
#Count of cases of each country
countires=latest_data.groupby('Country/Region')[['Confirmed','Deaths','Recovered','Active']].sum()
countires=countires.reset_index()
countires

         Country/Region  Confirmed  Deaths  Recovered  Active
0           Afghanistan      70111    2899      57281    9931
1               Albania     132297    2449     129215     633
2               Algeria     128456    3460      89419   35577
3               Andorra      13693     127      13416     150
4                Angola      34180     757      27646    5777
..                  ...        ...     ...        ...     ...
190             Vietnam       6908      47       2896    3965
191  West Bank and Gaza     307838    3492     300524    3822
192               Yemen       6731    1319       3399    2013
193              Zambia      94751    1276      91594    1881
194            Zimbabwe      38933    1594      36578     761

[195 rows x 5 columns]

In [ ]:
#Cases in India
countires[countires['Country/Region']=="India"]

   Country/Region  Confirmed  Deaths  Recovered   Active
78          India   27894800  325972   25454320  2114508

In [ ]:
### Plot on World map
import plotly.express as px
world_map=px.choropleth(countires,locations='Country/Region',locationmode='country names',color='Confirmed',hover_name='Country/Region',title='Confirmed Cases')
world_map.show()

In [ ]:
## Top contries having maximum confirmed and recovered cases
top=latest_data.groupby('Country/Region')[['Confirmed','Recovered']].sum().reset_index()
top=top.sort_values(['Confirmed'],ascending=False)
top.head()

    Country/Region  Confirmed  Recovered
182             US   33251939          0
78           India   27894800   25454320
23          Brazil   16471600   14496224
60          France    5719877     390878
180         Turkey    5235978    5094279

In [ ]:
### India
india=data[data["Country/Region"]=="India"]
india

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Active
446,447,2020-01-30,NaN,India,1/30/20 16:00,1,0,0,1
509,510,2020-01-31,NaN,India,1/31/2020 23:59,1,0,0,1
567,568,2020-02-01,NaN,India,1/31/2020 8:15,1,0,0,1
629,630,2020-02-02,NaN,India,2020-02-02T06:03:08,2,0,0,2
696,697,2020-02-03,NaN,India,2020-02-03T21:43:02,3,0,0,3
...,...,...,...,...,...,...,...,...,...
306351,306352,2021-05-29,Tripura,India,2021-05-30 04:20:55,50739,507,43190,7042
306366,306367,2021-05-29,Unknown,India,2021-05-30 04:20:55,0,0,0,0
306377,306378,2021-05-29,Uttar Pradesh,India,2021-05-30 04:20:55,1688152,20208,1621743,46201
306378,306379,2021-05-29,Uttarakhand,India,2021-05-30 04:20:55,327112,6360,289642,31110
306406,306407,2021-05-29,West Bengal,India,2021-05-30 04:20:55,1354956,15268,1237290,102398

In [ ]:
#Find the total number of states
india['Province/State'].nunique()

38

In [ ]:
#Names of the state
india['Province/State'].unique()

array([nan, 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Unknown', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [ ]:
#Replace Nan and Unknown by mode

mode_ = india['Province/State'].mode()[0]
india['Province/State'] = india['Province/State'].replace('Unknown', mode_)
india['Province/State'].unique()

/tmp/ipykernel_14986/4017801361.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [ ]:
## India latest Data
india_latest_data=india[india['ObservationDate']==india['ObservationDate'].max()]
india_latest_data

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Active
305855,305856,2021-05-29,Andaman and Nicobar Islands,India,2021-05-30 04:20:55,6964,113,6660,191
305856,305857,2021-05-29,Andhra Pradesh,India,2021-05-30 04:20:55,1671742,10738,1487382,173622
305873,305874,2021-05-29,Arunachal Pradesh,India,2021-05-30 04:20:55,26778,114,22746,3918
305874,305875,2021-05-29,Assam,India,2021-05-30 04:20:55,403623,3245,344083,56295
305896,305897,2021-05-29,Bihar,India,2021-05-30 04:20:55,704173,5052,678036,21085
305930,305931,2021-05-29,Chandigarh,India,2021-05-30 04:20:55,59740,740,56534,2466
305937,305938,2021-05-29,Chhattisgarh,India,2021-05-30 04:20:55,967645,12979,911752,42914
305956,305957,2021-05-29,Dadra and Nagar Haveli and Daman and Diu,India,2021-05-30 04:20:55,10214,4,9877,333
305960,305961,2021-05-29,Delhi,India,2021-05-30 04:20:55,1424646,24073,1387538,13035
305996,305997,2021-05-29,Goa,India,2021-05-30 04:20:55,154419,2597,136766,15056
306012,306013,2021-05-29,Gujarat,India,2021-05-30 04:20:55,805617,9790,757124,38703
306018,306019,2021-05-29,Haryana,India,2021-05-30 04:20:55,753937,8132,722711,23094
306025,306026,2021-05-29,Himachal Pradesh,India,2021-05-30 04:20:55,188604,3086,168529,16989
306051,306052,2021-05-29,Jammu and Kashmir,India,2021-05-30 04:20:55,286684,3841,243588,39255
306054,306055,2021-05-29,Jharkhand,India,2021-05-30 04:20:55,336240,4958,320336,10946
306072,306073,2021-05-29,Karnataka,India,2021-05-30 04:20:55,2567449,28298,2189064,350087
306075,306076,2021-05-29,Kerala,India,2021-05-30 04:20:55,2494385,8455,2252505,233425
306100,306101,2021-05-29,Ladakh,India,2021-05-30 04:20:55,18448,187,16658,1603
306101,306102,2021-05-29,Lakshadweep,India,2021-05-30 04:20:55,7631,31,5622,1978
306121,306122,2021-05-29,Madhya Pradesh,India,2021-05-30 04:20:55,777349,7959,738491,30899
306127,306128,2021-05-29,Maharashtra,India,2021-05-30 04:20:55,5713215,94030,5339838,279347
306129,306130,2021-05-29,Manipur,India,2021-05-30 04:20:55,48850,776,40044,8030
306142,306143,2021-05-29,Meghalaya,India,2021-05-30 04:20:55,34448,551,26156,7741
306156,306157,2021-05-29,Mizoram,India,2021-05-30 04:20:55,11988,36,8863,3089
306168,306169,2021-05-29,Nagaland,India,2021-05-30 04:20:55,21371,350,16039,4982
306212,306213,2021-05-29,Odisha,India,2021-05-30 04:20:55,747143,2686,658646,85811
306246,306247,2021-05-29,Puducherry,India,2021-05-30 04:20:55,102896,1497,88246,13153
306250,306251,2021-05-29,Punjab,India,2021-05-30 04:20:55,562831,14305,506349,42177
306260,306261,2021-05-29,Rajasthan,India,2021-05-30 04:20:55,936162,8251,871283,56628
306309,306310,2021-05-29,Sikkim,India,2021-05-30 04:20:55,14907,247,10829,3831
306330,306331,2021-05-29,Tamil Nadu,India,2021-05-30 04:20:55,2039716,23261,1706298,310157
306334,306335,2021-05-29,Telangana,India,2021-05-30 04:20:55,574026,3247,533862,36917
306351,306352,2021-05-29,Tripura,India,2021-05-30 04:20:55,50739,507,43190,7042
306366,306367,2021-05-29,Andaman and Nicobar Islands,India,2021-05-30 04:20:55,0,0,0,0
306377,306378,2021-05-29,Uttar Pradesh,India,2021-05-30 04:20:55,1688152,20208,1621743,46201
306378,306379,2021-05-29,Uttarakhand,India,2021-05-30 04:20:55,327112,6360,289642,31110
306406,306407,2021-05-29,West Bengal,India,2021-05-30 04:20:55,1354956,15268,1237290,102398

In [ ]:
## State having maximum cases
top_state=india_latest_data.groupby('Province/State')[["Confirmed",'Recovered']].sum().reset_index()
top_state=top_state.sort_values(['Confirmed'],ascending=False)
top_state.head(20)

    Province/State  Confirmed  Recovered
20     Maharashtra    5713215    5339838
15       Karnataka    2567449    2189064
16          Kerala    2494385    2252505
30      Tamil Nadu    2039716    1706298
33   Uttar Pradesh    1688152    1621743
1   Andhra Pradesh    1671742    1487382
8            Delhi    1424646    1387538
35     West Bengal    1354956    1237290
6     Chhattisgarh     967645     911752
28       Rajasthan     936162     871283
10         Gujarat     805617     757124
19  Madhya Pradesh     777349     738491
11         Haryana     753937     722711
25          Odisha     747143     658646
4            Bihar     704173     678036
31       Telangana     574026     533862
27          Punjab     562831     506349
3            Assam     403623     344083
14       Jharkhand     336240     320336
34     Uttarakhand     327112     289642

In [ ]:
top_state['Confirmed'].max()

5713215

In [ ]:
top_state[top_state["Confirmed"]==top_state['Confirmed'].max()]["Province/State"].values[0]

'Maharashtra'